# The enterprise account id
enterprise_id: "xxxxxxxxxxxxxxxxxxxxxx"

# IMPORTANT
# You can target the accounts with either account_group_id or account_list
# To share across account group with a list of accounts, provide account_group_id
# To share a specific list of accounts, provide account ids as a list in account_list
# Do not provide both account_group_id & account_list

# ID of the parent account group.
account_group_id: "xxxxxxxxxxxxxxxxxxxxxx"

# List of account IDs to target.
account_list:

# The import or delete operation to be performed for the custom PowerVS boot image. Accepted values are: IMPORT & DELETE.
image_operation: "IMPORT"

# The name under which the boot image is visible in the PowerVS workspace, along with the license_type, product, and vendor details for SAP images. License type supported values: 'byol'; product supported values: 'Hana', 'Netweaver'; vendor allowable value: 'SAP'. When not using SAP images, license_type, product and vendor can be left empty. Image_name should not be empty.
image_details:
  image_name: "test-image"
  license_type: "byol"
  product: "Hana"
  vendor: "SAP"

# Cloud Object Storage bucket name, region and file name. Required only when the image operation is IMPORT.
cos_bucket_details:
  cos_region: "eu-de"
  cos_bucket: "xxxxxxxxxxxxxxxxxxxxxx"
  cos_image_file_name: "rh-9-2-sap-2703.ova.gz"

# File names for logs
log_operation_file_name: "pi_image_ops_log.json"
log_status_file_name: "pi_image_status_log.json"

# Int value for multiprocessing on child accounts in parallel
processes: 8
