# The enterprise account id
enterprise_id: "bb9cf7ad84ba4e95af1ffe4ee060f255"

# IMPORTANT
# You can target the accounts with either account_group_id or account_list
# To share across account group with a list of accounts, provide account_group_id
# To share a specific list of accounts, provide account ids as a list in account_list
# Do not provide both account_group_id & account_list

account_group_id: "4993d44c96a94a75b95f73075f787f59"

# The list of account pr
account_list:

image_operation: "DELETE"

image_import_details:
  image_name: "my-image-catalog-name"
  license_type: ""
  product: ""
  vendor: ""

cos_bucket_details:
  cos_region: ""
  cos_bucket: ""
  cos_image_file_name: "rh-9-2-sap-2703.ova.gz"

log_operation_file_name: "pi_image_manager_log.json"

log_image_status_file_name: "pi_image_status_log.json"
