type: object
properties:
  enterprise_id:
    type: string
    minLength: 1
  account_group_id:
    type: string
  account_list:
    type: array
    items:
      type: string
  image_operation:
    type: string
    enum: ["IMPORT", "STATUS", "DELETE"]
  image_import_details:
    type: object
    properties:
      image_name:
        type: string
        minLength: 1
      license_type:
        type: string
      product:
        type: string
      vendor:
        type: string
    allOf:
      - if:
          properties:
            license_type:
              minLength: 1
        then:
          required: ["product", "vendor"]
      - if:
          properties:
            product:
              minLength: 1
        then:
          required: ["license_type", "vendor"]
      - if:
          properties:
            vendor:
              minLength: 1
        then:
          required: ["license_type", "product"]
    required: ["image_name"]
  cos_bucket_details:
    type: object
    properties:
      cos_region:
        type: string
      cos_bucket:
        type: string
      cos_image_file_name:
        type: string
  log_operation_file_name:
    type: string
  log_image_status_file_name:
    type: string
required: ["enterprise_id", "image_operation", "image_import_details"]
oneOf:
  - required: ["account_group_id"]
    properties:
      account_list:
        maxItems: 0
  - required: ["account_list"]
    properties:
      account_group_id:
        maxLength: 0
